"use client";

import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, Coffee, CreditCard, Plus, Search, ShoppingBag, Trash2, UserRound, WalletCards, X } from "lucide-react";
import Link from "next/link";

const money = (n:number) => `₹${n.toLocaleString("en-IN", { maximumFractionDigits: 0 })}`;
type MenuProduct = { id:string; category:string; name:string; price:number; active:boolean };

type Customer = { id:string; name:string|null; email:string; pointsBalance:number; stamps:number; visits:number; totalSpend:number };
type Item = { name:string; price:number; qty:number };

export default function POSPage() {
  const [query,setQuery]=useState(""); const [customers,setCustomers]=useState<Customer[]>([]); const [customer,setCustomer]=useState<Customer|null>(null);
  const [menu,setMenu]=useState<MenuProduct[]>([]); const [items,setItems]=useState<Item[]>([]); const [payment,setPayment]=useState("CASH"); const [busy,setBusy]=useState(false); const [done,setDone]=useState<any>(null); const [error,setError]=useState("");
  useEffect(()=>{fetch("/api/cafe/menu").then(r=>r.ok?r.json():[]).then(setMenu).catch(()=>setMenu([]))},[]);
  const total=useMemo(()=>items.reduce((s,i)=>s+i.price*i.qty,0),[items]);
  async function searchCustomers(v:string){ setQuery(v); setCustomer(null); if(v.trim().length<2){setCustomers([]);return;} const r=await fetch(`/api/cafe/customers?q=${encodeURIComponent(v)}`); if(r.ok)setCustomers(await r.json()); }
  function addItem(product:{name:string;price:number}){setItems(prev=>{const f=prev.find(i=>i.name===product.name);return f?prev.map(i=>i.name===product.name?{...i,qty:i.qty+1}:i):[...prev,{...product,qty:1}]})}
  function clear(){setItems([]);setCustomer(null);setQuery("");setCustomers([]);setPayment("CASH");setDone(null);setError("");}
  async function complete(){
    setError(""); if(!customer){setError("Select a customer first.");return;} if(!items.length){setError("Add at least one item.");return;} setBusy(true);
    const r=await fetch("/api/cafe/transactions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({customerId:customer.id,amount:total,paymentMethod:payment,items})});
    const d=await r.json(); setBusy(false); if(!r.ok){setError(d.error||"Could not complete order.");return;} setDone(d); setItems([]);
  }
  return <div className="mx-auto max-w-[1400px]">
    <div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="badge">Counter</div><h1 className="mt-2 text-3xl font-black tracking-tight">New order</h1><p className="muted mt-1 text-sm">Fast checkout for your café team. Loyalty updates automatically.</p></div><div className="flex gap-2"><Link href="/admin/transactions" className="btn soft">Order history</Link><button onClick={clear} className="btn soft">Clear</button></div></div>
    <div className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]">
      <section className="card overflow-hidden"><div className="border-b border-[var(--line)] p-5"><div className="mb-3 flex items-center gap-2 text-sm font-black"><UserRound size={17}/> Customer</div><div className="relative"><Search className="absolute left-4 top-3.5 text-[var(--muted)]" size={18}/><input value={query} onChange={e=>searchCustomers(e.target.value)} className="input pl-11" placeholder="Search name, email or customer code"/>{query&&<button onClick={()=>{setQuery("");setCustomers([])}} className="absolute right-3 top-2.5 rounded-lg p-1.5 text-[var(--muted)]"><X size={16}/></button>}</div>{customers.length>0&&!customer&&<div className="mt-2 overflow-hidden rounded-2xl border border-[var(--line)] bg-white">{customers.map(c=><button key={c.id} onClick={()=>{setCustomer(c);setQuery(c.name||c.email);setCustomers([])}} className="flex w-full items-center justify-between border-b border-[var(--line)] p-3 text-left last:border-0 hover:bg-[var(--soft)]"><span><span className="block text-sm font-extrabold">{c.name||"Unnamed customer"}</span><span className="text-xs text-[var(--muted)]">{c.email}</span></span><span className="text-xs font-black text-[var(--brown)]">{c.pointsBalance} pts</span></button>)}</div>}{customer&&<div className="mt-3 flex items-center justify-between rounded-2xl bg-[var(--soft)] p-4"><div><div className="font-black">{customer.name||customer.email}</div><div className="mt-1 text-xs text-[var(--muted)]">{customer.email} · {customer.visits} visits</div></div><div className="text-right"><div className="font-black text-[var(--brown)]">{customer.pointsBalance} pts</div><div className="text-xs text-[var(--muted)]">{customer.stamps} stamps</div></div></div>}</div>
      <div className="p-5"><div className="mb-3 flex items-center gap-2 text-sm font-black"><Coffee size={17}/> Quick add</div><div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{menu.filter(p=>p.active).map(p=><button key={p.name} onClick={()=>addItem(p)} className="rounded-2xl border border-[var(--line)] bg-white p-3 text-left transition hover:-translate-y-0.5 hover:border-[var(--gold)]"><div className="text-sm font-extrabold">{p.name}</div><div className="mt-1 text-xs font-black text-[var(--brown)]">{money(p.price)}</div></button>)}</div>{menu.filter(p=>p.active).length===0&&<div className="mt-3 rounded-xl bg-[var(--soft)] p-3 text-xs font-bold">No active menu items. Add them in <Link href="/admin/menu" className="underline">Menu manager</Link>.</div>}</div></section>
      <section className="card h-fit overflow-hidden lg:sticky lg:top-24"><div className="border-b border-[var(--line)] p-5"><div className="flex items-center justify-between"><div className="flex items-center gap-2 text-sm font-black"><ShoppingBag size={17}/> Current order</div><span className="badge">{items.reduce((s,i)=>s+i.qty,0)} items</span></div></div><div className="min-h-[220px] p-5">{!items.length?<div className="grid min-h-[190px] place-items-center text-center"><div><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-[var(--soft)]"><ShoppingBag className="text-[var(--brown)]"/></div><div className="mt-3 font-black">Your order is empty</div><div className="mt-1 text-xs text-[var(--muted)]">Add products from the menu.</div></div></div>:<div className="space-y-3">{items.map(i=><div key={i.name} className="flex items-center gap-3"><div className="min-w-0 flex-1"><div className="truncate text-sm font-extrabold">{i.name}</div><div className="text-xs text-[var(--muted)]">{money(i.price)} × {i.qty}</div></div><div className="font-black">{money(i.price*i.qty)}</div><button onClick={()=>setItems(items.filter(x=>x.name!==i.name))} className="icon-btn"><Trash2 size={15}/></button></div>)}</div>}</div><div className="border-t border-[var(--line)] p-5"><div className="flex items-center justify-between"><span className="text-sm font-bold text-[var(--muted)]">Total</span><span className="text-2xl font-black">{money(total)}</span></div><div className="mt-4 grid grid-cols-4 gap-2">{[["CASH","Cash"],["UPI","UPI"],["CARD","Card"],["OTHER","Other"]].map(([v,l])=><button key={v} onClick={()=>setPayment(v)} className={`rounded-xl border px-2 py-2 text-xs font-black ${payment===v?"border-[var(--brown)] bg-[var(--brown)] text-white":"border-[var(--line)] bg-white"}`}><CreditCard className="mx-auto mb-1" size={15}/>{l}</button>)}</div>{error&&<div className="mt-3 rounded-xl bg-red-50 p-3 text-xs font-bold text-red-700">{error}</div>}{done&&<div className="mt-3 rounded-2xl bg-emerald-50 p-4 text-emerald-900"><div className="flex items-center gap-2 font-black"><CheckCircle2 size={18}/> Order {done.orderNumber} complete</div><div className="mt-2 text-sm">{done.customer?.name||done.customer?.email} earned <b>+{done.pointsEarned} points</b> and <b>+{done.stampsEarned} stamp</b>.</div>{done.completedCards>0&&<div className="mt-2 text-xs font-black">🎉 Stamp card completed — {done.completedCards} reward cycle{done.completedCards>1?"s":""} unlocked.</div>}</div>}<button disabled={busy||!customer||!items.length} onClick={complete} className="btn primary mt-4 w-full py-3.5 text-sm">{busy?"Completing…":<><CheckCircle2 size={18}/> Complete order</>}</button></div></section>
    </div>
  </div>
}
