"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { AdminShell } from "@/components/AdminShell";
import { Users, UserRoundCheck, Clock3, Cake, Crown, Sparkles, ArrowRight } from "lucide-react";
const icons:any={ALL:Users,VIP:Crown,INACTIVE_30:Clock3,NEW_30:UserRoundCheck,BIRTHDAY_7:Cake,POINTS_500:Sparkles};
export default function CRM(){
 const [segments,setSegments]=useState<any[]>([]),[loading,setLoading]=useState(true);
 useEffect(()=>{fetch("/api/cafe/segments").then(r=>r.json()).then(setSegments).finally(()=>setLoading(false));},[]);
 return <AdminShell><div className="flex flex-wrap items-end justify-between gap-4"><div><span className="badge">Customer intelligence</span><h1 className="mt-3 text-3xl font-black sm:text-4xl">Know who to bring back.</h1><p className="mt-2 max-w-2xl text-sm leading-6 muted">Turn customer data into simple actions: reward your best customers, welcome new ones and win back people who have gone quiet.</p></div><Link href="/admin/campaigns" className="btn primary">Create campaign <ArrowRight size={16}/></Link></div>
 <div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{loading?[1,2,3,4,5,6].map(i=><div className="card h-40 animate-pulse" key={i}/>):segments.map(s=>{const I=icons[s.key]||Users;return <div className="card p-5" key={s.key}><div className="flex items-start justify-between"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-[var(--soft)] text-[var(--brown)]"><I size={20}/></div><span className="badge">{s.key.replaceAll("_"," ")}</span></div><div className="mt-5 text-3xl font-black">{s.count}</div><div className="mt-1 text-sm font-bold">{s.label}</div><Link href={`/admin/customers?segment=${s.key}`} className="mt-4 inline-flex items-center gap-2 text-xs font-black text-[var(--brown)]">View customers <ArrowRight size={14}/></Link></div>})}</div>
 <div className="mt-6 grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><div className="card p-6"><div className="text-[10px] font-black uppercase tracking-widest muted">Retention playbook</div><h2 className="mt-2 text-xl font-black">Three campaigns to run every month</h2><div className="mt-5 grid gap-3">{[["Win back","INACTIVE_30","Offer a small points bonus to customers who haven't visited in 30 days."],["Celebrate","BIRTHDAY_7","Send a personal birthday reward before their special day."],["Reward loyalty","VIP","Give high-value regulars early access to new offers or perks."]].map(x=><div className="rounded-2xl border border-[var(--line)] p-4" key={x[0]}><div className="flex items-center justify-between"><b>{x[0]}</b><span className="badge">{x[1]}</span></div><p className="mt-2 text-sm leading-6 muted">{x[2]}</p></div>)}</div></div><div className="card bg-[var(--brown)] p-6 text-white"><div className="text-[10px] font-black uppercase tracking-widest text-white/45">Next step</div><h2 className="mt-2 text-2xl font-black">Make retention automatic.</h2><p className="mt-3 text-sm leading-6 text-white/65">Phase 5 lays the foundation for email campaigns and customer segments. Scheduled birthday and win-back jobs can run on top of the same audience rules.</p><Link href="/admin/campaigns" className="mt-5 inline-flex items-center gap-2 rounded-xl bg-white px-4 py-3 text-xs font-black text-[var(--brown)]">Open campaigns <ArrowRight size={14}/></Link></div></div>
 </AdminShell>
}
