"use client";
import { useEffect, useState } from "react";
import { AdminShell } from "@/components/AdminShell";
import { Send, Users, Sparkles, Cake, Clock3, Crown } from "lucide-react";
const audiences:any={ALL:"All customers",VIP:"VIP customers",INACTIVE_30:"Inactive 30+ days",NEW_30:"New in 30 days",BIRTHDAY_7:"Birthdays in 7 days",POINTS_500:"500+ points"};
export default function Campaigns(){
 const [rows,setRows]=useState<any[]>([]),[segments,setSegments]=useState<any[]>([]),[f,setF]=useState({name:"",type:"WIN_BACK",message:"Hi {{name}}, we miss you! Come back and enjoy a little extra loyalty love.",bonusPoints:50,minDaysAway:30,audience:"INACTIVE_30"}),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
 async function load(){const [a,b]=await Promise.all([fetch("/api/cafe/campaigns"),fetch("/api/cafe/segments")]);setRows(await a.json());setSegments(await b.json())} useEffect(()=>{load()},[]);
 async function add(){setNotice("");setBusy(true);try{const r=await fetch("/api/cafe/campaigns",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(f)});const d=await r.json();if(!r.ok)throw new Error(d.error);setF({...f,name:""});setNotice("Campaign created. You can send it to the selected audience below.");load()}catch(e){setNotice(e instanceof Error?e.message:"Unable to create campaign.")}finally{setBusy(false)}}
 async function send(id:string,segment:string){setNotice("");setBusy(true);try{const r=await fetch(`/api/cafe/campaigns/${id}/send`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({segment})});const d=await r.json();if(!r.ok)throw new Error(d.error);setNotice(`${d.sent} email${d.sent===1?"":"s"} ${d.simulated?"simulated (add Resend to send for real)":"sent"}.`);load()}catch(e){setNotice(e instanceof Error?e.message:"Unable to send campaign.")}finally{setBusy(false)}}
 return <AdminShell><div className="flex flex-wrap items-end justify-between gap-4"><div><span className="badge">Retention CRM</span><h1 className="mt-3 text-3xl font-black sm:text-4xl">Campaigns that know who to talk to.</h1><p className="mt-2 max-w-2xl text-sm leading-6 muted">Create one message, choose an audience, and send a focused email instead of blasting every customer.</p></div></div>
 {notice&&<div className="mt-5 rounded-2xl border border-[var(--line)] bg-[var(--soft)] p-4 text-sm font-bold">{notice}</div>}
 <div className="mt-7 grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><div className="card p-6"><div className="flex items-center gap-2 font-black"><Sparkles size={18}/> Create campaign</div><div className="mt-5 grid gap-3"><input className="input" placeholder="Campaign name" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><select className="input" value={f.type} onChange={e=>setF({...f,type:e.target.value})}><option value="WIN_BACK">Win-back</option><option value="BIRTHDAY">Birthday</option><option value="ANNIVERSARY">Anniversary</option><option value="BONUS_POINTS">Bonus points</option><option value="GENERAL">General offer</option></select><select className="input" value={f.audience} onChange={e=>setF({...f,audience:e.target.value})}>{Object.entries(audiences).map(([k,v])=><option value={k} key={k}>{v as string}</option>)}</select><textarea className="input min-h-32" placeholder="Message. Use {{name}} for first name." value={f.message} onChange={e=>setF({...f,message:e.target.value})}/><div className="grid grid-cols-2 gap-3"><input className="input" type="number" min="0" placeholder="Bonus points" value={f.bonusPoints} onChange={e=>setF({...f,bonusPoints:+e.target.value})}/><input className="input" type="number" min="0" placeholder="Inactive days" value={f.minDaysAway} onChange={e=>setF({...f,minDaysAway:+e.target.value})}/></div><button disabled={busy||!f.name.trim()} className="btn primary justify-center" onClick={add}>Create campaign</button></div></div>
 <div className="grid gap-3">{rows.length===0?<div className="card p-10 text-center muted">No campaigns yet. Create your first retention campaign.</div>:rows.map(x=><div className="card p-5" key={x.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="text-lg font-black">{x.name}</div><div className="mt-1 text-xs muted">{x.type} · {x.recipientCount||0} sent {x.sentAt?`· ${new Date(x.sentAt).toLocaleString()}`:"· not sent"}</div></div><span className="badge">{audiences[x.audience]||"All customers"}</span></div><p className="mt-3 text-sm leading-6 text-[#75665c]">{x.message}</p><div className="mt-4 flex flex-wrap items-center gap-2"><select className="input max-w-xs" defaultValue={x.audience||"ALL"} id={`seg-${x.id}`}>{segments.map(s=><option value={s.key} key={s.key}>{s.label} ({s.count})</option>)}</select><button disabled={busy} className="btn primary" onClick={()=>send(x.id,(document.getElementById(`seg-${x.id}`) as HTMLSelectElement).value)}><Send size={15}/> Send</button></div></div>)}</div></div>
 </AdminShell>
}
