"use client";
import { useEffect, useState } from "react";
import { CustomerShell } from "@/components/CustomerShell";
import Link from "next/link";

export default function Membership({params}:{params:Promise<{slug:string}>}){const [slug,setSlug]=useState('');const [data,setData]=useState<any>(null);const [busy,setBusy]=useState(false);const [msg,setMsg]=useState('');useEffect(()=>{params.then(x=>{setSlug(x.slug);fetch('/api/customer/membership').then(r=>r.json()).then(setData).catch(()=>setData({}))})},[params]);
 if(!data)return <CustomerShell slug={slug} cafeName="Café"><div className="card p-8">Loading membership…</div></CustomerShell>;
 if(data.error) return <CustomerShell slug={slug} cafeName="Café"><div className="card p-8"><h2 className="text-xl font-black">Sign in to manage membership</h2><p className="mt-2 muted">Verify your email first, then return here to join or manage your membership.</p><Link href={`/login?cafe=${slug}`} className="btn gold mt-5">Sign in</Link></div></CustomerShell>;
 const c=data.config,m=data.membership,b=JSON.parse(c?.benefitsJson||'[]');
 async function action(a:'JOIN'|'CANCEL'){setBusy(true);setMsg('');const r=await fetch('/api/customer/membership',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:a})});const j=await r.json();if(j.url){window.location.href=j.url;return;}setMsg(j.message||j.error||'Unable to update membership.');if(r.ok)fetch('/api/customer/membership').then(r=>r.json()).then(setData);setBusy(false)}
 return <CustomerShell slug={slug} cafeName="Your café"><span className="badge">Membership</span><h1 className="mt-3 text-3xl font-black">More value from every visit.</h1>{!c?.active?<div className="card mt-6 p-8"><h2 className="text-xl font-black">Membership unavailable</h2><p className="mt-2 muted">This café hasn't opened memberships yet.</p></div>:<div className="mt-6 overflow-hidden rounded-[30px] bg-[var(--brown)] p-7 text-white shadow-2xl"><div className="text-xs font-black uppercase tracking-widest text-[#d99a35]">{c.name}</div><div className="mt-3 text-3xl font-black">{m?.status==='ACTIVE'?'You're a member':c.name}</div><div className="mt-3 text-4xl font-black">₹{c.price}<span className="text-sm text-white/45"> / {c.durationDays} days</span></div><div className="mt-7 grid gap-2">{b.map((x:string)=><div className="rounded-xl bg-white/10 p-3 text-sm" key={x}>✓ {x}</div>)}</div>{m?.status==='ACTIVE'?<><div className="mt-6 rounded-2xl bg-white/10 p-4 text-sm">Active until <b>{m.expiresAt?new Date(m.expiresAt).toLocaleDateString('en-IN'):''}</b></div><button className="btn mt-4 w-full bg-white/10 text-white" disabled={busy} onClick={()=>action('CANCEL')}>Cancel membership</button></>:<button className="btn gold mt-7 w-full" disabled={busy} onClick={()=>action('JOIN')}>{busy?'Processing…':c.price>0?`Join for ₹${c.price}`:'Join free'}</button>}{msg&&<p className="mt-4 text-sm font-bold text-[#ffd98d]">{msg}</p>}</div>}</CustomerShell>}
