import { NextResponse } from "next/server";
import { z } from "zod";
import { requirePermission } from "@/lib/permissions";
import { db } from "@/lib/db";
import { assertSameOrigin, assertJsonBody, clientKey, rateLimit, rateLimitResponse } from "@/lib/security";
import { audit } from "@/lib/audit";

const schema=z.object({code:z.string().trim().min(3).max(32).transform(v=>v.toUpperCase().replace(/\s+/g,"-")),title:z.string().trim().min(2).max(100),description:z.string().trim().max(300).optional(),type:z.enum(["PERCENTAGE","FIXED_AMOUNT","FREE_ITEM"]),value:z.number().positive().max(100000).optional(),minSpend:z.number().nonnegative().max(1000000).default(0),maxDiscount:z.number().positive().max(1000000).optional(),usageLimit:z.number().int().positive().max(10000000).optional(),perCustomerLimit:z.number().int().positive().max(100).default(1),startsAt:z.string().datetime().optional(),expiresAt:z.string().datetime().optional(),active:z.boolean().default(true)}).superRefine((v,ctx)=>{if(v.type!=="FREE_ITEM"&&!v.value)ctx.addIssue({code:"custom",path:["value"],message:"Value is required for this offer."});if(v.type==="PERCENTAGE"&&v.value! >100)ctx.addIssue({code:"custom",path:["value"],message:"Percentage cannot exceed 100."});if(v.expiresAt&&v.startsAt&&new Date(v.expiresAt)<=new Date(v.startsAt))ctx.addIssue({code:"custom",path:["expiresAt"],message:"Expiry must be after start."});});
export async function GET(){try{const s=await requirePermission("CAMPAIGNS");return NextResponse.json(await db.offer.findMany({where:{cafeId:s.user.cafeId!},orderBy:{createdAt:"desc"},take:200}));}catch{return NextResponse.json({error:"Unauthorized."},{status:401});}}
export async function POST(req:Request){if(!assertJsonBody(req))return rateLimitResponse(60,"Request body is invalid or too large.");const rl=await rateLimit(clientKey(req,"offers"),20,60000);if(!rl.ok)return rateLimitResponse(rl.retryAfter);if(!assertSameOrigin(req))return NextResponse.json({error:"Invalid request origin."},{status:403});try{const s=await requirePermission("CAMPAIGNS");const cafeId=s.user.cafeId!;const b=schema.parse(await req.json());const exists=await db.offer.findUnique({where:{cafeId_code:{cafeId,code:b.code}}});if(exists)return NextResponse.json({error:"That offer code already exists."},{status:409});const offer=await db.offer.create({data:{cafeId,code:b.code,title:b.title,description:b.description||null,type:b.type,value:b.value??null,minSpend:b.minSpend,maxDiscount:b.maxDiscount??null,usageLimit:b.usageLimit??null,perCustomerLimit:b.perCustomerLimit,startsAt:b.startsAt?new Date(b.startsAt):null,expiresAt:b.expiresAt?new Date(b.expiresAt):null,active:b.active}});await audit(cafeId,s.user.id,"OFFER_CREATED","Offer",offer.id,{code:offer.code,type:offer.type});return NextResponse.json(offer,{status:201});}catch(e){if(e instanceof z.ZodError)return NextResponse.json({error:e.issues[0]?.message||"Invalid offer."},{status:400});return NextResponse.json({error:"Unable to create offer."},{status:500});}}
