import { AdminShell } from "@/components/AdminShell";
import { StatCard } from "@/components/StatCard";
import { cafeAdmin } from "@/lib/auth";
import { db } from "@/lib/db";
import Link from "next/link";
import { ArrowRight, Gift, Megaphone, QrCode, Users, ReceiptText, Sparkles } from "lucide-react";

export default async function Admin(){
 const s=await cafeAdmin(); if(s.user.role==="SUPER_ADMIN") return <Super/>;
 const c=await db.cafe.findUnique({where:{id:s.user.cafeId!},include:{subscription:{include:{plan:true}},features:true}}); if(!c) return null;
 const w={cafeId:c.id};
 const [n,t,r,f]=await Promise.all([db.customer.count({where:w}),db.transaction.count({where:w}),db.reward.count({where:{...w,active:true}}),db.feedback.aggregate({where:w,_avg:{rating:true}})]);
 const rev=(await db.transaction.aggregate({where:w,_sum:{amount:true}}))._sum.amount||0;
 const recent=await db.transaction.findMany({where:w,include:{customer:true},orderBy:{createdAt:"desc"},take:6});
 return <AdminShell cafeName={c.name}>
   <div className="flex flex-wrap items-start justify-between gap-5"><div><span className="badge">Good morning</span><h1 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Your café at a glance.</h1><p className="mt-2 max-w-2xl text-sm leading-6 muted">See what is happening with your customers, then take the next useful action.</p></div><div className="flex flex-wrap gap-2"><Link href="/admin/onboarding" className="btn soft">Setup checklist</Link><Link href="/admin/pos" className="btn primary">New order <ArrowRight size={16}/></Link></div></div>
   <div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><StatCard label="Customers" value={String(n)} sub="Registered here" icon="👥"/><StatCard label="Revenue" value={`₹${rev.toLocaleString("en-IN")}`} sub="Recorded orders" icon="₹"/><StatCard label="Orders" value={String(t)} sub="All-time recorded" icon="🧾"/><StatCard label="Rating" value={f._avg.rating?.toFixed(1)||"—"} sub="Customer feedback" icon="★"/></div>
   <div className="mt-6 grid gap-6 xl:grid-cols-[1.4fr_.6fr]">
    <div className="card overflow-hidden"><div className="flex items-center justify-between border-b border-[var(--line)] p-5"><div><h2 className="font-black">Latest customer activity</h2><p className="mt-1 text-xs muted">Recent orders and loyalty earned.</p></div><Link href="/admin/transactions" className="text-xs font-black text-[var(--brown)]">View all →</Link></div>{recent.length===0?<div className="p-10 text-center"><div className="text-4xl">☕</div><div className="mt-3 font-black">Your first order is waiting.</div><div className="mt-1 text-sm muted">Record a transaction to start building customer history.</div></div>:recent.map(x=><div key={x.id} className="flex items-center justify-between gap-4 border-b border-[var(--line)] p-5 last:border-0"><div className="flex min-w-0 items-center gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-2xl bg-[var(--soft)] font-black text-[var(--brown)]">{(x.customer.name||x.customer.email).slice(0,1).toUpperCase()}</div><div className="min-w-0"><div className="truncate font-black">{x.customer.name||x.customer.email}</div><div className="mt-1 text-xs muted">{x.orderNumber}</div></div></div><div className="text-right"><div className="font-black">₹{x.amount.toLocaleString("en-IN")}</div><div className="mt-1 text-xs font-bold text-[#8b621f]">+{x.pointsEarned} pts · +{x.stampsEarned} stamp</div></div></div>)}</div>
    <div className="grid gap-4"><div className="card p-5"><div className="text-[10px] font-black uppercase tracking-widest muted">Next best actions</div><div className="mt-4 grid gap-2">{[[QrCode,"Set up your QR","Make joining effortless","/admin/qr"],[Gift,"Create a reward","Give customers a reason to return","/admin/rewards"],[Megaphone,"Run a campaign","Bring inactive customers back","/admin/campaigns"]].map(([I,t,d,h])=>{const Icon=I as any;return <Link href={h as string} key={t as string} className="group flex gap-3 rounded-2xl border border-[var(--line)] p-3 hover:bg-[var(--soft)]"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[var(--soft)] text-[var(--brown)]"><Icon size={18}/></div><div className="min-w-0"><div className="text-sm font-black">{t as string}</div><div className="mt-1 text-xs leading-5 muted">{d as string}</div></div><ArrowRight className="ml-auto mt-2 shrink-0 opacity-30 group-hover:opacity-100" size={15}/></Link>})}</div></div><div className="card bg-[var(--brown)] p-5 text-white"><div className="text-[10px] font-black uppercase tracking-widest text-white/45">Loyalty setup</div><div className="mt-2 text-lg font-black">{r} active rewards</div><div className="mt-1 text-xs leading-5 text-white/55">Your current loyalty features are ready for customers.</div><Link href="/admin/loyalty" className="mt-4 inline-flex items-center gap-2 text-xs font-black text-[#f0c36b]">Tune your rules <ArrowRight size={14}/></Link></div></div>
   </div>
 </AdminShell>
}
async function Super(){const[c,s,p]=await Promise.all([db.cafe.count(),db.subscription.count({where:{status:"ACTIVE"}}),db.plan.count()]);return <AdminShell superAdmin><span className="badge">Platform admin</span><h1 className="mt-3 text-3xl font-black">CafeClub control center</h1><p className="mt-1 muted">Manage tenants, plans and subscriptions.</p><div className="mt-7 grid gap-4 md:grid-cols-3"><StatCard label="Cafés" value={String(c)} sub="Tenants" icon="☕"/><StatCard label="Active subs" value={String(s)} sub="Paying/active access" icon="✓"/><StatCard label="Plans" value={String(p)} sub="Billing catalog" icon="◇"/></div></AdminShell>}
