import { test, expect } from "@playwright/test";
const routes = ["/", "/signup", "/login", "/pricing"];
test.describe("PUBLIC - 25 tests", () => {
  test("01 home loads", async ({page}) => { await page.goto("/"); await expect(page.locator("body")).toBeVisible(); });
  test("02 signup loads", async ({page}) => { await page.goto("/signup"); await expect(page.locator("body")).toBeVisible(); });
  test("03 login loads", async ({page}) => { await page.goto("/login"); await expect(page.locator("body")).toBeVisible(); });
  test("04 pricing loads", async ({page}) => { await page.goto("/pricing"); await expect(page.locator("body")).toBeVisible(); });
  test("05 unknown route handled", async ({page}) => { const r=await page.goto("/qa-nonexistent-route"); expect(r?.status()??0).toBeLessThan(500); });
  test("06 home has content", async ({page}) => { await page.goto("/"); expect((await page.locator("body").innerText()).length).toBeGreaterThan(20); });
  test("07 signup has form controls", async ({page}) => { await page.goto("/signup"); expect(await page.locator("input").count()).toBeGreaterThan(0); });
  test("08 login has email", async ({page}) => { await page.goto("/login"); await expect(page.getByLabel(/email/i)).toBeVisible(); });
  test("09 login has slug", async ({page}) => { await page.goto("/login"); await expect(page.getByLabel(/slug/i)).toBeVisible(); });
  test("10 login has action", async ({page}) => { await page.goto("/login"); expect(await page.getByRole("button").count()).toBeGreaterThan(0); });
  test("11 signup has name field", async ({page}) => { await page.goto("/signup"); expect(await page.locator("input").count()).toBeGreaterThanOrEqual(3); });
  test("12 pricing has plan content", async ({page}) => { await page.goto("/pricing"); expect((await page.locator("body").innerText()).toLowerCase()).toMatch(/starter|growth|pro/); });
  test("13 homepage internal links are present", async ({page}) => { await page.goto("/"); expect(await page.locator("a[href]").count()).toBeGreaterThan(0); });
  test("14 no homepage horizontal fatal blank", async ({page}) => { await page.goto("/"); expect((await page.locator("body").innerText()).trim()).not.toBe(""); });
  test("15 signup renders without page error", async ({page}) => { const e:string[]=[]; page.on("pageerror",x=>e.push(x.message)); await page.goto("/signup"); expect(e).toEqual([]); });
  test("16 login renders without page error", async ({page}) => { const e:string[]=[]; page.on("pageerror",x=>e.push(x.message)); await page.goto("/login"); expect(e).toEqual([]); });
  test("17 pricing renders without page error", async ({page}) => { const e:string[]=[]; page.on("pageerror",x=>e.push(x.message)); await page.goto("/pricing"); expect(e).toEqual([]); });
  test("18 home returns non-500", async ({request}) => { expect((await request.get("/")).status()).toBeLessThan(500); });
  test("19 signup returns non-500", async ({request}) => { expect((await request.get("/signup")).status()).toBeLessThan(500); });
  test("20 login returns non-500", async ({request}) => { expect((await request.get("/login")).status()).toBeLessThan(500); });
  test("21 pricing returns non-500", async ({request}) => { expect((await request.get("/pricing")).status()).toBeLessThan(500); });
  test("22 internal home links are same-origin or external", async ({page}) => { await page.goto("/"); const bad=await page.locator("a[href]").evaluateAll(as=>as.some(a=>{try{return new URL((a as HTMLAnchorElement).href).origin!==location.origin && !/^https?:/.test((a as HTMLAnchorElement).href)}catch{return true}})); expect(bad).toBeFalsy(); });
  test("23 signup page is not blank", async ({page}) => { await page.goto("/signup"); expect((await page.locator("body").innerText()).trim().length).toBeGreaterThan(20); });
  test("24 pricing page is not blank", async ({page}) => { await page.goto("/pricing"); expect((await page.locator("body").innerText()).trim().length).toBeGreaterThan(20); });
  test("25 login page is not blank", async ({page}) => { await page.goto("/login"); expect((await page.locator("body").innerText()).trim().length).toBeGreaterThan(20); });
});
