import { test, expect } from "@playwright/test";
import { OWNER, CUSTOMER, SUPERADMIN, platformRoutes, login } from "./helpers";

test.describe("SECURITY - 45 tests", () => {
  test("116 anonymous cafe transactions rejected", async ({request}) => { expect((await request.get("/api/cafe/transactions")).status()).toBeGreaterThanOrEqual(401); });
  test("117 anonymous customers rejected", async ({request}) => { expect((await request.get("/api/cafe/customers")).status()).toBeGreaterThanOrEqual(401); });
  test("118 anonymous menu rejected", async ({request}) => { expect((await request.get("/api/cafe/menu")).status()).toBeGreaterThanOrEqual(401); });
  test("119 anonymous loyalty rejected", async ({request}) => { expect((await request.get("/api/cafe/loyalty")).status()).toBeGreaterThanOrEqual(401); });
  test("120 anonymous rewards rejected", async ({request}) => { expect((await request.get("/api/cafe/rewards")).status()).toBeGreaterThanOrEqual(401); });
  test("121 anonymous responses aren't 500", async ({request}) => { for(const x of ["/api/cafe/transactions","/api/cafe/customers","/api/cafe/menu","/api/cafe/loyalty","/api/cafe/rewards"]) expect((await request.get(x)).status()).toBeLessThan(500); });
  test("122 health isn't 500", async ({request}) => { expect((await request.get("/api/health")).status()).toBeLessThan(500); });
  test("123 readiness is 200 or local 503", async ({request}) => { expect([200,503]).toContain((await request.get("/api/readiness")).status()); });
  test("124 empty OTP request rejected", async ({request}) => { const s=(await request.post("/api/auth/request-otp",{data:{}})).status(); expect(s).toBeGreaterThanOrEqual(400); expect(s).toBeLessThan(500); });
  test("125 malformed transaction JSON rejected safely", async ({request}) => { const s=(await request.post("/api/cafe/transactions",{headers:{"content-type":"application/json"},data:"{bad"})).status(); expect(s).toBeGreaterThanOrEqual(400); expect(s).toBeLessThan(500); });
  test("126 invalid OTP rejected", async ({request}) => { await request.post("/api/auth/request-otp",{data:{email:OWNER.email,cafeSlug:OWNER.slug}}); const s=(await request.post("/api/auth/verify-otp",{data:{email:OWNER.email,cafeSlug:OWNER.slug,otp:"000000"}})).status(); expect(s).toBeGreaterThanOrEqual(400); expect(s).toBeLessThan(500); });
  test("127 owner reaches admin root", async ({page}) => { await login(page,OWNER); await page.goto("/admin"); expect(page.url()).toMatch(/\/admin/); });
  test("128 owner denied platform analytics", async ({page}) => { await login(page,OWNER); await page.goto(platformRoutes[0]); expect(page.url()).not.toContain(platformRoutes[0]); });
  test("129 owner denied cafes platform page", async ({page}) => { await login(page,OWNER); await page.goto(platformRoutes[1]); expect(page.url()).not.toContain(platformRoutes[1]); });
  test("130 owner denied plans platform page", async ({page}) => { await login(page,OWNER); await page.goto(platformRoutes[2]); expect(page.url()).not.toContain(platformRoutes[2]); });
  test("131 owner denied subscriptions platform page", async ({page}) => { await login(page,OWNER); await page.goto(platformRoutes[3]); expect(page.url()).not.toContain(platformRoutes[3]); });
  test("132 customer denied admin root", async ({page}) => { await login(page,CUSTOMER); await page.goto("/admin"); expect(page.url()).not.toMatch(/\/admin(?:\/|$)/); });
  test("133 customer denied platform analytics", async ({page}) => { await login(page,CUSTOMER); await page.goto("/admin/platform-analytics"); expect(page.url()).not.toContain("platform-analytics"); });
  test("134 customer denied plans", async ({page}) => { await login(page,CUSTOMER); await page.goto("/admin/plans"); expect(page.url()).not.toContain("/admin/plans"); });
  test("135 customer denied subscriptions", async ({page}) => { await login(page,CUSTOMER); await page.goto("/admin/subscriptions"); expect(page.url()).not.toContain("/admin/subscriptions"); });
  test("136 superadmin can reach platform analytics", async ({page}) => { await login(page,SUPERADMIN); await page.goto("/admin/platform-analytics"); expect(page.url()).toContain("platform-analytics"); });
  test("137 superadmin can reach cafes", async ({page}) => { await login(page,SUPERADMIN); await page.goto("/admin/cafes"); expect(page.url()).toContain("/admin/cafes"); });
  test("138 superadmin can reach plans", async ({page}) => { await login(page,SUPERADMIN); await page.goto("/admin/plans"); expect(page.url()).toContain("/admin/plans"); });
  test("139 superadmin can reach subscriptions", async ({page}) => { await login(page,SUPERADMIN); await page.goto("/admin/subscriptions"); expect(page.url()).toContain("/admin/subscriptions"); });
  test("140 tenant query cannot change owner route", async ({page}) => { await login(page,OWNER); await page.goto("/admin/customers?cafeId=other"); expect(page.url()).toContain("/admin/customers"); });
  test("141 tenant query cannot change transaction route", async ({page}) => { await login(page,OWNER); await page.goto("/admin/transactions?cafeId=other"); expect(page.url()).toContain("/admin/transactions"); });
  test("142 tenant query cannot change menu route", async ({page}) => { await login(page,OWNER); await page.goto("/admin/menu?cafeId=other"); expect(page.url()).toContain("/admin/menu"); });
  test("143 tenant query cannot change rewards route", async ({page}) => { await login(page,OWNER); await page.goto("/admin/rewards?cafeId=other"); expect(page.url()).toContain("/admin/rewards"); });
  test("144 tenant query cannot change analytics route", async ({page}) => { await login(page,OWNER); await page.goto("/admin/analytics?cafeId=other"); expect(page.url()).toContain("/admin/analytics"); });
  test("145 customer unknown cafe isn't bean wallet", async ({page}) => { await login(page,CUSTOMER); await page.goto("/c/no-such-cafe"); expect(page.url()).not.toContain("/c/bean-and-bloom"); });
  test("146 logout endpoint exists", async ({request}) => { const s=(await request.post("/api/auth/logout")).status(); expect(s).toBeLessThan(500); });
  test("147 anonymous logout doesn't crash", async ({request}) => { const s=(await request.post("/api/auth/logout")).status(); expect(s).toBeLessThan(500); });
  test("148 protected GETs don't return 2xx anonymously", async ({request}) => { for(const x of ["/api/cafe/transactions","/api/cafe/customers","/api/cafe/menu","/api/cafe/loyalty","/api/cafe/rewards"]) expect((await request.get(x)).status()).not.toBeLessThan(300); });
  test("149 auth request endpoint isn't a server crash", async ({request}) => { expect((await request.post("/api/auth/request-otp",{data:{email:"bad",cafeSlug:"bad"}})).status()).toBeLessThan(500); });
  test("150 auth verify endpoint isn't a server crash", async ({request}) => { expect((await request.post("/api/auth/verify-otp",{data:{email:"bad",cafeSlug:"bad",otp:"bad"}})).status()).toBeLessThan(500); });
  test("151 sensitive malformed input never returns 500", async ({request}) => { for(const x of ["/api/auth/request-otp","/api/auth/verify-otp","/api/cafe/transactions"]) { const s=(await request.post(x,{headers:{"content-type":"application/json"},data:"not-json"})).status(); expect(s,x).toBeLessThan(500); } });
  test("152 owner doesn't become customer after login", async ({page}) => { await login(page,OWNER); expect(page.url()).not.toContain("/c/"); });
  test("153 customer doesn't become owner after login", async ({page}) => { await login(page,CUSTOMER); expect(page.url()).not.toMatch(/\/admin/); });
  test("154 superadmin doesn't become customer after login", async ({page}) => { await login(page,SUPERADMIN); expect(page.url()).not.toContain("/c/"); });
  test("155 platform routes are all protected candidates", async () => { expect(platformRoutes.every(x=>x.startsWith("/admin/"))).toBeTruthy(); });
  test("156 owner role has no platform route in expected route set", async () => { expect(platformRoutes.some(x=>x==="/admin")).toBeFalsy(); });
  test("157 customer slug is tenant-specific", async () => { expect(CUSTOMER.slug).toBe("bean-and-bloom"); });
  test("158 owner slug is tenant-specific", async () => { expect(OWNER.slug).toBe("bean-and-bloom"); });
  test("159 superadmin test identity is separate", async () => { expect(SUPERADMIN.email).not.toBe(OWNER.email); });
  test("160 customer test identity is separate", async () => { expect(CUSTOMER.email).not.toBe(OWNER.email); });
});
