"use client";
import { useEffect, useMemo, useState } from "react";
import { AdminShell } from "@/components/AdminShell";
import { Plus, Power, Trash2 } from "lucide-react";

type Item={id:string;category:string;name:string;description:string|null;price:number;active:boolean};
const money=(n:number)=>`₹${n.toLocaleString("en-IN",{maximumFractionDigits:0})}`;
export default function MenuPage(){
 const [items,setItems]=useState<Item[]>([]); const [f,setF]=useState({category:"Coffee",name:"",description:"",price:180}); const [busy,setBusy]=useState(false); const [msg,setMsg]=useState("");
 const load=async()=>{const r=await fetch("/api/cafe/menu");setItems(r.ok?await r.json():[])}; useEffect(()=>{load()},[]);
 const groups=useMemo(()=>items.filter(x=>x.active).reduce<Record<string,Item[]>>((acc,x)=>{(acc[x.category]??=[]).push(x);return acc},{}),[items]);
 async function add(){setMsg("");setBusy(true);const r=await fetch("/api/cafe/menu",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...f,price:Number(f.price)})});const j=await r.json();setBusy(false);if(!r.ok){setMsg(j.error||"Could not add item");return;}setF({...f,name:"",description:""});setMsg("Menu item added");load()}
 async function toggle(x:Item){await fetch(`/api/cafe/menu/${x.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({active:!x.active})});load()}
 async function remove(x:Item){if(!confirm(`Delete ${x.name}?`))return;await fetch(`/api/cafe/menu/${x.id}`,{method:"DELETE"});load()}
 return <AdminShell><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><span className="badge">Café operations</span><h1 className="mt-3 text-3xl font-black">Menu manager</h1><p className="mt-1 muted">Your menu powers the POS. Keep prices and availability up to date.</p></div><a href="/admin/pos" className="btn primary">Open POS →</a></div>
 <div className="mt-7 grid gap-6 lg:grid-cols-[360px_1fr]"><section className="card p-6"><div className="text-lg font-black">Add menu item</div><div className="mt-1 text-sm muted">It appears in the order screen immediately.</div><div className="mt-5 grid gap-3"><input className="input" placeholder="Item name" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><select className="input" value={f.category} onChange={e=>setF({...f,category:e.target.value})}><option>Coffee</option><option>Food</option><option>Breakfast</option><option>Desserts</option><option>Other</option></select><input className="input" placeholder="Short description" value={f.description} onChange={e=>setF({...f,description:e.target.value})}/><input className="input" type="number" min="1" value={f.price} onChange={e=>setF({...f,price:Number(e.target.value)})}/><button className="btn primary" disabled={busy||!f.name.trim()} onClick={add}><Plus size={16}/>{busy?"Adding…":"Add item"}</button>{msg&&<div className="rounded-xl bg-[var(--soft)] p-3 text-sm font-bold">{msg}</div>}</div></section>
 <section className="grid gap-5">{Object.entries(groups as Record<string,Item[]>).map(([cat,arr])=><div key={cat}><div className="mb-2 text-xs font-black uppercase tracking-widest muted">{cat}</div><div className="grid gap-3 sm:grid-cols-2">{arr.map(x=><div className="card flex items-center justify-between gap-3 p-5" key={x.id}><div><div className="font-black">{x.name}</div><div className="mt-1 text-sm muted">{x.description||"Available on POS"}</div><div className="mt-2 font-black">{money(x.price)}</div></div><div className="flex gap-2"><button className="icon-btn" title={x.active?"Disable":"Enable"} onClick={()=>toggle(x)}><Power size={16}/></button><button className="icon-btn" title="Delete" onClick={()=>remove(x)}><Trash2 size={16}/></button></div></div>)}</div></div>)}{items.filter(x=>!x.active).length>0&&<div><div className="mb-2 text-xs font-black uppercase tracking-widest muted">Disabled</div><div className="grid gap-3 sm:grid-cols-2">{items.filter(x=>!x.active).map(x=><div className="card flex items-center justify-between p-5 opacity-60" key={x.id}><div><div className="font-black">{x.name}</div><div className="text-sm muted">{money(x.price)}</div></div><button className="btn" onClick={()=>toggle(x)}>Enable</button></div>)}</div></div>}</section></div></AdminShell>
}
