"use client";
import { useEffect, useState } from "react";
import { AdminShell } from "@/components/AdminShell";
import { Save, Sparkles } from "lucide-react";

type Feature={id:string;feature:string;enabled:boolean;configJson:string};
export default function LoyaltyPage(){
 const [rows,setRows]=useState<Feature[]>([]); const [points,setPoints]=useState({pointsPerRupee:0.1,minOrder:50}); const [stamps,setStamps]=useState({stampsPerOrder:1,stampsToReward:8}); const [msg,setMsg]=useState(""); const [busy,setBusy]=useState(false);
 useEffect(()=>{fetch("/api/cafe/settings").then(r=>r.json()).then((d:Feature[])=>{setRows(d);const p=d.find(x=>x.feature==="LOYALTY_POINTS");const s=d.find(x=>x.feature==="STAMP_CARD");try{if(p)setPoints({...points,...JSON.parse(p.configJson||"{}")});if(s)setStamps({...stamps,...JSON.parse(s.configJson||"{}")})}catch{}})},[]);
 const feature=(name:string)=>rows.find(x=>x.feature===name);
 async function save(featureName:string,config:object){setBusy(true);const r=await fetch("/api/cafe/settings",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({feature:featureName,enabled:true,config})});const j=await r.json();setBusy(false);setMsg(r.ok?"Loyalty settings saved.":j.error||"Could not save settings.");}
 async function toggle(name:string){const x=feature(name);if(!x)return;await fetch("/api/cafe/settings",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({feature:name,enabled:!x.enabled})});setRows(rows.map(r=>r.feature===name?{...r,enabled:!r.enabled}:r));}
 return <AdminShell><div><span className="badge">Loyalty control</span><h1 className="mt-3 text-3xl font-black">Make every visit count.</h1><p className="mt-1 muted">Simple rules your team can understand and your customers can feel.</p></div>
 <div className="mt-7 grid gap-5 lg:grid-cols-2"><section className="card p-6"><div className="flex items-start justify-between"><div><div className="flex items-center gap-2 text-lg font-black"><Sparkles size={18}/> Points</div><p className="mt-1 text-sm muted">Reward customers based on eligible spend.</p></div><button className={`badge ${feature("LOYALTY_POINTS")?.enabled?"":"opacity-50"}`} onClick={()=>toggle("LOYALTY_POINTS")}>{feature("LOYALTY_POINTS")?.enabled?"Enabled":"Off"}</button></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold">Points per ₹1<input className="input mt-2" type="number" step="0.01" min="0" value={points.pointsPerRupee} onChange={e=>setPoints({...points,pointsPerRupee:Number(e.target.value)})}/></label><label className="text-sm font-bold">Minimum order<input className="input mt-2" type="number" min="0" value={points.minOrder} onChange={e=>setPoints({...points,minOrder:Number(e.target.value)})}/></label></div><button disabled={busy} className="btn primary mt-4" onClick={()=>save("LOYALTY_POINTS",points)}><Save size={16}/>Save points rules</button></section>
 <section className="card p-6"><div className="flex items-start justify-between"><div><div className="text-lg font-black">Stamp card</div><p className="mt-1 text-sm muted">Turn repeat visits into a visible progress bar.</p></div><button className="badge" onClick={()=>toggle("STAMP_CARD")}>{feature("STAMP_CARD")?.enabled?"Enabled":"Off"}</button></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold">Stamps per order<input className="input mt-2" type="number" min="1" value={stamps.stampsPerOrder} onChange={e=>setStamps({...stamps,stampsPerOrder:Number(e.target.value)})}/></label><label className="text-sm font-bold">Stamps to reward<input className="input mt-2" type="number" min="1" value={stamps.stampsToReward} onChange={e=>setStamps({...stamps,stampsToReward:Number(e.target.value)})}/></label></div><div className="mt-4 rounded-2xl bg-[var(--soft)] p-4 text-sm"><b>Example:</b> A customer earns {stamps.stampsPerOrder} stamp{stamps.stampsPerOrder===1?"":"s"} per eligible order and unlocks the card at {stamps.stampsToReward}.</div><button disabled={busy} className="btn primary mt-4" onClick={()=>save("STAMP_CARD",stamps)}><Save size={16}/>Save stamp rules</button></section></div>{msg&&<div className="mt-4 rounded-2xl bg-emerald-50 p-4 text-sm font-bold text-emerald-900">{msg}</div>}
 <div className="mt-6 card p-6"><div className="font-black">Games</div><p className="mt-1 text-sm muted">Enable or disable surprise features without changing the rest of your loyalty program.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{["SPIN_WHEEL","SCRATCH_CARD"].map(n=>{const x=feature(n);return <button key={n} onClick={()=>toggle(n)} className="flex items-center justify-between rounded-2xl border border-[var(--line)] p-4 text-left hover:bg-[var(--soft)]"><span><b>{n.replaceAll("_"," ")}</b><span className="mt-1 block text-xs muted">Customer-facing daily surprise</span></span><span className="badge">{x?.enabled?"On":"Off"}</span></button>})}</div></div>
 </AdminShell>;
}
