"use client";
import { useEffect, useState } from "react";
import { AdminShell } from "@/components/AdminShell";

export default function MembershipAdmin(){
 const [form,setForm]=useState({name:"Club Membership",price:0,durationDays:365,benefits:["Member-only perks","Birthday surprise","Early access to offers"],memberDiscountPercent:10,bonusPointsMultiplier:1.5,exclusiveRewards:false,active:true});
 const [stats,setStats]=useState<any>({}); const [saving,setSaving]=useState(false); const [msg,setMsg]=useState("");
 useEffect(()=>{fetch('/api/cafe/membership').then(r=>r.json()).then(x=>{if(x.config)setForm({name:x.config.name,price:x.config.price,durationDays:x.config.durationDays,benefits:JSON.parse(x.config.benefitsJson||'[]'),memberDiscountPercent:x.config.memberDiscountPercent||0,bonusPointsMultiplier:x.config.bonusPointsMultiplier||1,exclusiveRewards:Boolean(x.config.exclusiveRewards),active:x.config.active});setStats(Object.fromEntries((x.counts||[]).map((c:any)=>[c.status,c._count._all])))}).catch(()=>{});},[]);
 async function save(){setSaving(true);setMsg(""); const r=await fetch('/api/cafe/membership',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const j=await r.json();setMsg(r.ok?'Membership settings saved.':j.error||'Unable to save.');setSaving(false);}
 return <AdminShell><span className="badge">Retention engine</span><h1 className="mt-3 text-3xl font-black">Membership</h1><p className="mt-1 text-[#7c6d63]">Turn regular visitors into members with recurring perks and a clear lifecycle.</p>
 <div className="mt-6 grid gap-3 sm:grid-cols-4">{[['Active',stats.ACTIVE||0],['Pending',stats.PENDING||0],['Expired',stats.EXPIRED||0],['Canceled',stats.CANCELED||0]].map(([a,n])=><div className="card p-5" key={String(a)}><div className="text-xs font-black uppercase tracking-widest muted">{a}</div><div className="mt-2 text-3xl font-black">{n}</div></div>)}</div>
 <div className="mt-6 grid gap-6 lg:grid-cols-[1.05fr_.95fr]"><div className="card p-6"><h2 className="text-xl font-black">Membership plan</h2><div className="mt-5 grid gap-4"><label className="text-sm font-bold">Name<input className="input mt-2" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><div className="grid grid-cols-2 gap-3"><label className="text-sm font-bold">Price (₹)<input type="number" className="input mt-2" value={form.price} onChange={e=>setForm({...form,price:Number(e.target.value)})}/></label><label className="text-sm font-bold">Duration (days)<input type="number" className="input mt-2" value={form.durationDays} onChange={e=>setForm({...form,durationDays:Number(e.target.value)})}/></label></div><div className="grid grid-cols-2 gap-3"><label className="text-sm font-bold">Member discount (%)<input type="number" min="0" max="100" className="input mt-2" value={form.memberDiscountPercent} onChange={e=>setForm({...form,memberDiscountPercent:Number(e.target.value)})}/></label><label className="text-sm font-bold">Bonus points multiplier<input type="number" min="1" max="10" step="0.1" className="input mt-2" value={form.bonusPointsMultiplier} onChange={e=>setForm({...form,bonusPointsMultiplier:Number(e.target.value)})}/></label></div><label className="flex items-center gap-3 text-sm font-bold"><input type="checkbox" checked={form.exclusiveRewards} onChange={e=>setForm({...form,exclusiveRewards:e.target.checked})}/> Give members access to exclusive rewards</label><label className="text-sm font-bold">Benefits<textarea className="input mt-2 min-h-32" value={form.benefits.join('\n')} onChange={e=>setForm({...form,benefits:e.target.value.split('\n').map(x=>x.trim()).filter(Boolean)})}/><span className="mt-1 block text-xs muted">One benefit per line.</span></label><label className="flex items-center gap-3 text-sm font-bold"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Membership available to customers</label><button className="btn gold" onClick={save} disabled={saving}>{saving?'Saving…':'Save membership'}</button>{msg&&<p className="text-sm font-bold">{msg}</p>}</div></div>
 <div className="rounded-[28px] bg-[var(--brown)] p-7 text-white"><div className="text-xs font-black uppercase tracking-widest text-[#d99a35]">Customer preview</div><div className="mt-4 text-3xl font-black">{form.name}</div><div className="mt-3 text-4xl font-black">₹{form.price}<span className="text-sm text-white/45"> / {form.durationDays} days</span></div><div className="mt-6 grid gap-2">{form.benefits.map(x=><div className="rounded-xl bg-white/10 p-3 text-sm" key={x}>✓ {x}</div>)}</div><div className="mt-5 rounded-2xl bg-white/10 p-4 text-sm text-white/75"><b>{form.memberDiscountPercent}% member discount</b> · {form.bonusPointsMultiplier}× points{form.exclusiveRewards ? " · exclusive rewards" : ""}</div><div className="mt-3 rounded-2xl bg-white/10 p-4 text-sm text-white/65">{form.price>0?'Customers pay securely through Stripe before activation.':'Free memberships activate instantly.'}</div></div></div></AdminShell>
}
