import Link from "next/link";
import { ArrowRight, Check, Gift, QrCode, BarChart3, HeartHandshake, Smartphone, Sparkles } from "lucide-react";
import { Logo } from "@/components/Logo";

export default function Home(){return <main>
  <header className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-6"><Logo/><nav className="hidden items-center gap-7 text-sm font-bold text-[var(--muted)] md:flex"><a href="#how">How it works</a><a href="#features">Features</a><Link href="/pricing">Pricing</Link></nav><div className="flex items-center gap-2"><Link href="/login" className="btn soft">Log in</Link><Link href="/signup" className="btn primary">Start free</Link></div></header>
  <section className="mx-auto max-w-7xl px-5 pb-20 pt-12 sm:px-6 lg:pt-20"><div className="grid items-center gap-14 lg:grid-cols-[1.02fr_.98fr]">
    <div><span className="badge">Retention software for cafés</span><h1 className="mt-6 max-w-3xl text-5xl font-black leading-[.98] tracking-[-.045em] sm:text-6xl lg:text-7xl">Make your regulars feel like <span className="text-[#c88722]">regulars.</span></h1><p className="mt-6 max-w-xl text-base leading-7 text-[#75665c] sm:text-lg">CafeClub gives your café a branded loyalty wallet, simple order tracking and automated ways to bring customers back.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/signup" className="btn primary px-6">Create my café <ArrowRight size={17}/></Link><Link href="/c/bean-and-bloom" className="btn soft px-6">Preview customer wallet</Link></div><div className="mt-6 flex flex-wrap gap-x-6 gap-y-2 text-xs font-bold text-[var(--muted)]"><span>✓ 14-day trial</span><span>✓ No app download</span><span>✓ Your café, your brand</span></div></div>
    <div className="relative"><div className="absolute -inset-6 rounded-[40px] bg-[#ecd7b8]/30 blur-2xl"/><div className="relative overflow-hidden rounded-[32px] border border-[#3b271e] bg-[#241812] p-5 text-white shadow-2xl sm:p-7"><div className="flex items-center justify-between"><div><div className="text-[10px] font-black uppercase tracking-[.18em] text-white/45">Bean & Bloom</div><div className="mt-1 text-lg font-black">Retention cockpit</div></div><div className="rounded-full bg-white/10 px-3 py-1 text-[10px] font-black">This week</div></div><div className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-white/10 p-4"><div className="text-xs text-white/50">Repeat customers</div><div className="mt-2 text-3xl font-black">64%</div><div className="mt-1 text-xs font-bold text-[#e8b85f]">↑ 7.2%</div></div><div className="rounded-2xl bg-white/10 p-4"><div className="text-xs text-white/50">Revenue</div><div className="mt-2 text-3xl font-black">₹48.2k</div><div className="mt-1 text-xs font-bold text-[#e8b85f]">↑ 12.4%</div></div></div><div className="mt-3 rounded-2xl bg-white/10 p-4"><div className="flex justify-between text-xs font-bold"><span className="text-white/50">Customer retention health</span><span>Good</span></div><div className="mt-3 h-2 rounded-full bg-white/10"><div className="h-full w-[78%] rounded-full bg-[#d99a35]"/></div></div><div className="mt-3 grid grid-cols-3 gap-2"><div className="rounded-xl bg-white/10 p-3 text-center"><Gift size={17} className="mx-auto"/><div className="mt-2 text-[10px] font-bold">Rewards</div></div><div className="rounded-xl bg-white/10 p-3 text-center"><Sparkles size={17} className="mx-auto"/><div className="mt-2 text-[10px] font-bold">Loyalty</div></div><div className="rounded-xl bg-white/10 p-3 text-center"><BarChart3 size={17} className="mx-auto"/><div className="mt-2 text-[10px] font-bold">Insights</div></div></div></div></div>
  </div></section>
  <section id="features" className="border-y border-[#eadfd2] bg-white/40"><div className="mx-auto max-w-7xl px-5 py-14 sm:px-6"><div className="max-w-xl"><span className="badge">Everything in one place</span><h2 className="mt-4 text-3xl font-black tracking-tight sm:text-4xl">A loyalty system your team can actually use.</h2></div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[[QrCode,"One QR","Customers join without downloading an app."],[Gift,"Rewards","Points, stamps, offers, spin and scratch."],[HeartHandshake,"Retention","Win back customers and reward referrals."],[BarChart3,"Insights","See who returns, spends and engages."]].map(([Icon,title,desc])=>{const I=Icon as any;return <div className="card p-5" key={String(title)}><div className="grid h-11 w-11 place-items-center rounded-2xl bg-[var(--soft)] text-[var(--brown)]"><I size={20}/></div><div className="mt-5 font-black">{title as string}</div><div className="mt-2 text-sm leading-6 muted">{desc as string}</div></div>})}</div></div></section>
  <section id="how" className="mx-auto max-w-7xl px-5 py-16 sm:px-6"><div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><div><span className="badge">Simple for everyone</span><h2 className="mt-4 text-3xl font-black tracking-tight">Three experiences. One platform.</h2><p className="mt-4 leading-7 muted">CafeClub stays in the background. Your café brand stays in front of the customer.</p></div><div className="grid gap-3">{[["01","Café owner","Creates loyalty rules, rewards and QR codes."],["02","Customer","Scans, verifies email and gets a mobile wallet."],["03","Café team","Records orders and loyalty updates automatically."]].map(([n,t,d])=><div key={n} className="card flex gap-4 p-5 sm:p-6"><span className="badge h-fit">{n}</span><div><div className="font-black">{t}</div><div className="mt-1 text-sm leading-6 muted">{d}</div></div></div>)}</div></div></section>
  <section className="mx-auto max-w-7xl px-5 pb-20 sm:px-6"><div className="overflow-hidden rounded-[32px] bg-[var(--brown)] p-7 text-white sm:p-10"><div className="grid gap-8 md:grid-cols-[1fr_auto] md:items-end"><div><div className="text-[10px] font-black uppercase tracking-[.18em] text-white/45">Ready to build your regulars?</div><h2 className="mt-3 max-w-2xl text-3xl font-black sm:text-4xl">Start with your café. Add more sophistication as you grow.</h2></div><Link href="/signup" className="btn gold w-fit">Start 14-day trial <ArrowRight size={17}/></Link></div></div></section>
  <footer className="border-t border-[var(--line)]"><div className="mx-auto flex max-w-7xl flex-col gap-3 px-5 py-7 text-xs font-bold text-[var(--muted)] sm:flex-row sm:items-center sm:justify-between sm:px-6"><Logo/><span>© 2026 CafeClub · Customer retention for cafés</span></div></footer>
</main>}
