"use client";
import { useEffect, useState } from "react";
import { CustomerShell } from "@/components/CustomerShell";
export default function Settings({params}:{params:Promise<{slug:string}>}){
 const [slug,setSlug]=useState(""),[cafe,setCafe]=useState<any>(null),[opt,setOpt]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
 useEffect(()=>{params.then(async p=>{setSlug(p.slug);const r=await fetch(`/api/customer/cafe?slug=${encodeURIComponent(p.slug)}`);const d=await r.json();setCafe(d.cafe||null);const x=await fetch("/api/customer/settings");if(x.ok){const s=await x.json();setOpt(!!s.emailOptOut)}})},[params]);
 async function save(){setBusy(true);setNotice("");try{const r=await fetch("/api/customer/settings",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({emailOptOut:opt})});const d=await r.json();if(!r.ok)throw new Error(d.error);setNotice(opt?"Marketing emails are turned off.":"Marketing emails are turned on.")}catch(e){setNotice(e instanceof Error?e.message:"Unable to save preferences.")}finally{setBusy(false)}}
 if(!cafe)return <CustomerShell slug={slug} cafeName="Your café"><div className="card p-8">Loading settings…</div></CustomerShell>;
 return <CustomerShell slug={slug} cafeName={cafe.name} primaryColor={cafe.primaryColor} accentColor={cafe.accentColor}><span className="badge">Your preferences</span><h1 className="mt-3 text-3xl font-black">Email settings</h1><p className="mt-2 text-sm leading-6 muted">Choose whether this café can send you loyalty and promotional emails. Transactional messages may still be sent when necessary.</p><div className="card mt-6 p-6"><div className="flex items-start justify-between gap-5"><div><div className="font-black">Marketing emails</div><div className="mt-1 text-sm muted">Birthday treats, win-back offers and loyalty reminders.</div></div><button onClick={()=>setOpt(!opt)} className={`relative h-7 w-12 rounded-full transition ${opt?"bg-[var(--brown)]":"bg-black/15"}`} aria-label="Toggle marketing emails"><span className={`absolute top-1 h-5 w-5 rounded-full bg-white transition ${opt?"left-6":"left-1"}`}/></button></div><button disabled={busy} onClick={save} className="btn primary mt-6">{busy?"Saving…":"Save preferences"}</button>{notice&&<div className="mt-3 text-sm font-bold">{notice}</div>}</div></CustomerShell>
}
