"use client";
import { useEffect, useState } from "react";
import { AdminShell } from "@/components/AdminShell";
import { BellRing, Cake, Clock3, Gift, Play, UserPlus, CheckCircle2 } from "lucide-react";

const icons:any={BIRTHDAY:Cake,WIN_BACK_30:Clock3,FIRST_ORDER:UserPlus,REWARD_READY:Gift};
export default function Automations(){
 const [rows,setRows]=useState<any[]>([]),[runs,setRuns]=useState<any[]>([]),[busy,setBusy]=useState<string>(""),[notice,setNotice]=useState("");
 async function load(){const [a,b]=await Promise.all([fetch("/api/cafe/automations/settings"),fetch("/api/cafe/automations")]);setRows(await a.json());setRuns(await b.json())}
 useEffect(()=>{load()},[]);
 async function toggle(key:string,enabled:boolean){setBusy(key);setNotice("");try{const r=await fetch("/api/cafe/automations/settings",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({key,enabled})});if(!r.ok)throw new Error((await r.json()).error||"Unable to update");await load();}catch(e){setNotice(e instanceof Error?e.message:"Unable to update automation.")}finally{setBusy("")}}
 async function run(key:string){setBusy(key);setNotice("");try{const r=await fetch("/api/cafe/automations/run",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({key})});const d=await r.json();if(!r.ok)throw new Error(d.error);setNotice(d.skipped?(d.disabled?"Automation is turned off.":"Already run today."):`${d.sent} message${d.sent===1?"":"s"} ${d.simulated?"simulated":"sent"}${d.failed?` · ${d.failed} failed`:""}.`);load()}catch(e){setNotice(e instanceof Error?e.message:"Unable to run automation.")}finally{setBusy("")}}
 return <AdminShell><div><span className="badge">Always-on retention</span><h1 className="mt-3 text-3xl font-black sm:text-4xl">Automations that bring customers back.</h1><p className="mt-2 max-w-2xl text-sm leading-6 muted">Set the rules once. CafeClub checks eligible customers each day and sends a helpful email without your team having to remember.</p></div>
 {notice&&<div className="mt-5 rounded-2xl border border-[var(--line)] bg-[var(--soft)] p-4 text-sm font-bold">{notice}</div>}
 <div className="mt-7 grid gap-4">{rows.map(x=>{const Icon=icons[x.key]||BellRing;return <div className="card p-5" key={x.key}><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex gap-4"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-[var(--soft)] text-[var(--brown)]"><Icon size={21}/></div><div><div className="text-lg font-black">{x.name}</div><p className="mt-1 max-w-xl text-sm leading-6 muted">{x.description}</p></div></div><label className="flex cursor-pointer items-center gap-2 text-xs font-black"><input type="checkbox" checked={x.enabled} disabled={busy===x.key} onChange={e=>toggle(x.key,e.target.checked)}/>{x.enabled?"ON":"OFF"}</label></div><div className="mt-5 flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-[var(--soft)] p-4"><div><div className="text-[10px] font-black uppercase tracking-widest muted">Message</div><div className="mt-1 text-sm font-bold">{x.subject}</div></div><button className="btn primary" disabled={busy===x.key||!x.enabled} onClick={()=>run(x.key)}><Play size={15}/> Run now</button></div></div>})}</div>
 <div className="mt-8"><div className="flex items-center gap-2"><CheckCircle2 size={18}/><h2 className="text-xl font-black">Automation history</h2></div><div className="card mt-4 overflow-hidden"><div className="divide-y divide-[var(--line)]">{runs.length?runs.map(r=><div className="flex flex-wrap items-center justify-between gap-3 p-4" key={r.id}><div><div className="font-black">{r.key}</div><div className="text-xs muted">{new Date(r.createdAt).toLocaleString()}</div></div><div className="text-right text-sm font-bold">{r.status} · {r.sentCount} sent · {r.failedCount} failed</div></div>):<div className="p-8 text-center text-sm muted">No automation runs yet.</div>}</div></div></div>
 </AdminShell>
}
